# https://docs.travis-ci.com/user/languages/java/
# https://docs.travis-ci.com/user/reference/osx/
# https://docs.travis-ci.com/user/reference/windows/

language: java

addons:
  apt:  # only active on Linux
    packages:
      - ant

  hostname: jyshort

  
jobs:
  include:
    - name: "openjdk11 on Linux"
      os: linux
      jdk: openjdk11

    - name: "openjdk14 on Linux"
      os: linux
      jdk: openjdk14

    - name: "openjdk11 on macOS"
      os: osx
      osx_image: xcode11.6  # Supports homebrew bundle without update
      # https://travis-ci.community/t/macos-build-fails-because-of-homebrew-bundle-unknown-command/7296/26
      # https://docs.travis-ci.com/user/installing-dependencies/
      # https://github.com/AdoptOpenJDK/homebrew-openjdk
      addons:
        homebrew:
          taps:
            - AdoptOpenJDK/openjdk  # for Java
          casks:
            - adoptopenjdk11
      before_install:
        # Add the required JDK to the path
        - export JAVA_HOME="$(/usr/libexec/java_home -v11)"
        - echo $JAVA_HOME
        - export PATH="$JAVA_HOME/bin:$PATH"

# No installation, but check versions here
install:
  # Confirm versions and paths (this has been a problem)
  - echo $PATH
  - java -version
  - ./gradlew --version

# Cache artefacts downloaded by Gradle
# https://guides.gradle.org/executing-gradle-builds-on-travisci/#enable_caching_of_downloaded_artifacts
# (Caching may be flakey on Windows.)
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Run the build and post results via a build scan
script:
  - ./gradlew check
